service: lambda-twitter-blog-hook

frameworkVersion: '>=1.45.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'ap-southeast-1'}

  environment:
    HOOK_SECRET: ${file(env.yml):secrets.HOOK_SECRET}
    API_KEY: ${file(env.yml):secrets.API_KEY}
    API_SECRET: ${file(env.yml):secrets.API_SECRET}
    ACCESS_TOKEN: ${file(env.yml):secrets.ACCESS_TOKEN}
    ACCESS_SECRET: ${file(env.yml):secrets.ACCESS_SECRET}
    BASE_URL: ${file(env.yml):secrets.BASE_URL}

plugins:
  - serverless-plugin-scripts

custom:
  scripts:
    hooks:
      'package:initialize': make
      'deploy:finalize': make clean

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  blogposter:
    handler: bin/blogposter
    events:
      - http:
          path: status
          method: post
          cors: true
